osx_image: xcode8.2
language: objective-c
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
script:
- set -o pipefail && xcodebuild test -workspace Example/SwiftLuhn.xcworkspace -scheme SwiftLuhn-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' | xcpretty
- pod lib lint
