version: 2
jobs:
  build:
    macos:
      xcode: 9.4.1
    steps:
      - checkout
      - run: set -o pipefail && xcodebuild test -destination "platform=iOS Simulator,name=iPhone 7" -workspace Example/SwiftLuhn.xcworkspace -scheme SwiftLuhn-Example | xcpretty
      - run: pod lib lint --swift-version=4
